// <auto-generated />
namespace Assignment5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class create_media_item : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_media_item));
        
        string IMigrationMetadata.Id
        {
            get { return "202004160723060_create_media_item"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
