// <auto-generated />
namespace Assignment5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add_media_item_to_artist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_media_item_to_artist));
        
        string IMigrationMetadata.Id
        {
            get { return "202004160731431_add_media_item_to_artist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
