// <auto-generated />
namespace Assignment5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class track_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(track_update));
        
        string IMigrationMetadata.Id
        {
            get { return "202004152308221_track_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
