// <auto-generated />
namespace Assignment4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class create_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "202004080205261_create_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
